# Generated by Django 2.1.2 on 2018-10-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('index', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
